config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	resources :photos do 
	resources :comments
	end
	
	root 'photos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user 
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user

	has_one_attached :image
	has_many_attached :images
	has_many :comments 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :photos
   has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = current_user.comments.create(message_params.merge(photo_id: params[:photo_id]))
		if @comment.save
			redirect_to photo_url(@comment.photo)
		else 
			redirect_to root_urls
		end
	end

	def show 
		@comment = Comment.find(params[:id])
	end
	
	private
		def message_params
			params.require(:comment).permit(:message)		
		end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

 	def new 
 		@photo = Photo.new
 	end

 	def create 
 		@photo = current_user.photos.create(photo_params)
 	
 		if @photo.save
		 	redirect_to @photo
		else
			render :new
		end	
 	end
 	
 	def show
 		@photo = Photo.find(params[:id])
 		@comment = Comment.new
 	end

 	private 
 	def photo_params
 		params.require(:photo).permit(:caption, :image, images: [])
 	end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link href="https://fonts.googleapis.com/css?family=Lacquer&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Share+Tech+Mono&display=swap" rel="stylesheet">  

  </head>

  <body>

     <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

  <header>  
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" style="color: white;">Instagramv2</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/photos/new">Shortcut Line<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item disabled">
          <a class="nav-link aria" tabindex="-1" aria-disabled="true">simple web</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="in progress" aria-label="Enter Help">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Help</button>
      </form>
      </div>
    </nav>
  </header>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/photos/index.html.erb
<center>
<body style="background-color: #D0E11D;">

<div style="margin-top: 100px;">

<h1 style="font-family: 'Lacquer', sans-serif;">Hello Instagram (v2)</h1>

<p>Click the green to</p>


<% if current_user %>
		
		<%= link_to 'Logout' , destroy_user_session_path, method: :delete, style: "text-decoration: none; color: white;" "margin-top:-345px;" "margin-left:1200px;" , class:"button btn btn-danger" %>
		<br>

<div style="margin-top: -20px;">

		<ul class="list-unstyled list-inline">
		<%= link_to 'New Photo', new_photo_path , style: "text-decoration: none; color: white;" , class:"button btn btn-success"  %> 	
		<li class="list-inline-item">


	<% else %>

		<ul class="list-unstyled list-inline">
			<%= link_to 'Login', user_session_path , style: "text-decoration: none; color: white;" , class:"button btn btn-success" %><br><br>
		

		
			<%= link_to 'Register', new_user_registration_path , style: "text-decoration: none; color: white;", class:"button btn btn-success" %><br><br>
		<li class="list-inline-item">
				
	<% end %>
</div>
</div>
</body>

<center>
		<ul class="list-unstyled list-inline">
		<%= link_to 'Shortcut' ,  new_photo_path , style: "text-decoration: none; color: white;" "margin-top: 15px;" , class:"button btn btn-info" %>
		<p>Login first to make it all works</p>
		<li class="list-inline-item">
</center>
</center>

app/views/photos/new.html.erb
<div class="text-center">

<body style="background-color: #1CCEEE;"></body>

<div style="margin-top: 100px;"></div>

<h1 style="font-family: 'Lacquer'; font-size: 40px; ">New Photo</h1>

<%= form_for @photo do |form| %>

	<%= link_to 'Logout' , destroy_user_session_path, method: :delete, style: "text-decoration: none; color: white;" "margin-top:-260px;" "margin-left:1200px;" , class:"button btn btn-danger" %>

	<p>
	   <%= form.label :caption , style:"font-family: 'Share Tech Mono', monospace; font-size: 25px;" %><br>
	   <%= form.text_area :caption %>
	</p>

	<p>	
		<%= form.label :image %><br>
		<%= form.file_field :image %>
	</p>
	  
	<p>	
		<%= form.label :images %><br>
		<%= form.file_field :images, multiple: true %>
	</p>

	<p>
	   <%= form.submit 'Enter' %>
	</p>

<% end %>
</div>

app/views/photos/show.html.erb
<body style="background-color: #EBEECA;">

<div style="margin-top: 40px;">

<%= link_to 'Logout' , destroy_user_session_path, method: :delete, style: "text-decoration: none; color: white;" "margin-top:-30px;" "margin-left:1200px;", class:"button btn btn-danger" %>

<button type="button" style="margin-left: 220px; margin-top: -25px;" class="btn btn-primary">
  Profile <span class="badge badge-light">7</span>
  <span class="sr-only">unread messages</span>
</button>


<div class="container">
	 <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <% if @photo.image.attached? %> 
			<%= image_tag @photo.image , class:"img-fluid" %>
			<% end %>
            <div class="card-body">
              <p class="card-text"><%= @photo.caption %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
     </div>   #little bug

<% if @photo.images.attached? %>
	<div class="row">
		<% @photo.images.each do |image| %>
		<div class="col-md-4">
          <div class="card mb-4 shadow-sm">
 			<%= image_tag image , class:"img-fluid" %>	
            <div class="card-body">
              <p class="card-text"><%= @photo.caption %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
          </div>	

 	<% end %>	
			
	
 <% else %>
 	<p style="font-family: 'share tech mono', monospace;">enter your comment :</p>
 <% end %>

<ul>	
 <% if @photo.comments.any? %>
	<% @photo.comments.each do |comment| %>
		<li>
		<h4><%= comment.message %><span class="badge badge-success" style="font-family: monospace; margin-left:7px;">New	
	 	</span></h4>
	 	</li>
 	<% end %>
 <% end %>
</ul>

 <%= form_for @comment, url: photo_comments_path(@photo) do |form| %>
 	<%= form.label :message, style:"font-family: 'share tech mono', monospace;" %>
 	<%= form.text_area :message %>

	<%= form.submit 'Submit', class:"btn btn-success" , style:"font-family: 'share tech mono', monospace;" %>
<% end %>
</div>
</body>

app/views/users/user.html.erb
<p>code isnt work in this file</p>

app/views/users/users.html.erb
<h1>Instagram Web</h1>
<br>
<% if current_user %>
	<%= link_to 'Logout', destroy_user_session_path, method: :delete %>

	<br>
		<%= link_to 'New Photo', new_photo_path %> 
	
	<% else %>
	
		<%= link_to 'Login', new_user_session_path %>

		<%= link_to 'Register', new_user_session_path %>

	<% end %>